[package]
name = "yawcli"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = "2.33"
reqwest = {version = "0.11", features = ["blocking", "json"]}
scraper = "0.13"
serde = {version = "1.0", features = ["derive"] }

[dev-dependencies]
assert_cmd = "2"
predicates = "2.1.4"
